/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intermediario;


import java.util.ArrayList;


/**
 *
 * @author andre
 */
public class Interfaz extends javax.swing.JFrame {

    private  ArrayList<String> secuencia_perdida;
   
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        this.radio_normal.setSelected(true);//Default
        this.radio_group.add(this.radio_normal);
        this.radio_group.add(this.radio_debug);
        
        this.perderBtn.setEnabled(false);
        secuencia_perdida = new ArrayList<String>();
        
        this.textArea.setEditable(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio_group = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cliente_intermediario = new javax.swing.JTextField();
        intermediario_servidor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        servidor_intermediario = new javax.swing.JTextField();
        intermediario_cliente = new javax.swing.JTextField();
        listoBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        probabilidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        radio_normal = new javax.swing.JRadioButton();
        radio_debug = new javax.swing.JRadioButton();
        perderBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Servidor -> Servidor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cliente -> Servidor");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Puerto Cliente-Intermediario");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Puerto Intermediario-Servidor");

        cliente_intermediario.setBackground(new java.awt.Color(255, 160, 160));
        cliente_intermediario.setText("10000");
        cliente_intermediario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente_intermediarioActionPerformed(evt);
            }
        });

        intermediario_servidor.setBackground(new java.awt.Color(128, 255, 0));
        intermediario_servidor.setText("10003");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Puerto Servidor-Intermediario");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Puerto Intermediario-Cliente");

        servidor_intermediario.setBackground(new java.awt.Color(255, 255, 0));
        servidor_intermediario.setText("10002");

        intermediario_cliente.setBackground(new java.awt.Color(149, 237, 255));
        intermediario_cliente.setText("10001");

        listoBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        listoBtn.setText("Listo");
        listoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Intermediario");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Probabilidad [0,1]");

        probabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probabilidadActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Modo");

        radio_normal.setText("Normal");
        radio_normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_normalActionPerformed(evt);
            }
        });

        radio_debug.setText("Debug");
        radio_debug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_debugActionPerformed(evt);
            }
        });

        perderBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        perderBtn.setText("Perder!");
        perderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(45, 45, 45)
                        .addComponent(radio_normal)
                        .addGap(18, 18, 18)
                        .addComponent(radio_debug))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(40, 40, 40)
                            .addComponent(cliente_intermediario))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(intermediario_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(listoBtn)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(intermediario_cliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(servidor_intermediario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(probabilidad))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(perderBtn)
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cliente_intermediario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(intermediario_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(servidor_intermediario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(intermediario_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(probabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(radio_normal)
                            .addComponent(radio_debug))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listoBtn)
                    .addComponent(perderBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cliente_intermediarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente_intermediarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente_intermediarioActionPerformed

    private void listoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoBtnActionPerformed
        try
        {
            boolean normal = this.radio_normal.isSelected();
            Servidor_Servidor servidor = new Servidor_Servidor(normal, this.textArea, Integer.parseInt(this.servidor_intermediario.getText()), Integer.parseInt(this.intermediario_cliente.getText()), Double.parseDouble(this.probabilidad.getText()));
            Servidor_Cliente cliente = new Servidor_Cliente(normal,this.secuencia_perdida,this.textArea, Double.parseDouble(this.probabilidad.getText()), Integer.parseInt(this.cliente_intermediario.getText()), Integer.parseInt(this.intermediario_servidor.getText()));
            
            servidor.start();
            cliente.start();
        }
        catch(Exception e)
        {
            System.err.println("Error fatal al iniciar los hilos. Es probable que los datos ingresados no sean los correctos");
        }
        
    }//GEN-LAST:event_listoBtnActionPerformed

    private void perderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perderBtnActionPerformed
        int arrayLength;
        String texto = this.textArea.getText();
        String array[] = texto.split(",");
        arrayLength = array.length;
        
        for(int i = 0; i < arrayLength; ++i) //Agregamos los paquetes a la blackList
        {
            secuencia_perdida.add(array[i]+":.");
        }
        
        this.listoBtn.setEnabled(true);
    }//GEN-LAST:event_perderBtnActionPerformed

    private void radio_normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_normalActionPerformed
        this.listoBtn.setEnabled(true);
        this.perderBtn.setEnabled(false);
        this.textArea.setEditable(false);
        this.textArea.setText("");
        this.probabilidad.setText("");
    }//GEN-LAST:event_radio_normalActionPerformed

    private void radio_debugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_debugActionPerformed
        this.perderBtn.setEnabled(true);
        this.listoBtn.setEnabled(false);
        this.textArea.setEditable(true);
        this.textArea.setText("Separe con comas la secuencia de números.\nPor ejemplo: 0, 1");
        this.probabilidad.setText("0");
    }//GEN-LAST:event_radio_debugActionPerformed

    private void probabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probabilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_probabilidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cliente_intermediario;
    private javax.swing.JTextField intermediario_cliente;
    private javax.swing.JTextField intermediario_servidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listoBtn;
    private javax.swing.JButton perderBtn;
    private javax.swing.JTextField probabilidad;
    private javax.swing.JRadioButton radio_debug;
    private javax.swing.ButtonGroup radio_group;
    private javax.swing.JRadioButton radio_normal;
    private javax.swing.JTextField servidor_intermediario;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
