/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jean
 */
public class interfaz_cliente extends javax.swing.JFrame {
    Cliente cliente;
    Boolean modo;
    /**
     * Creates new form interfaz_cliente
     */
    public interfaz_cliente() {
        initComponents();
        cliente = new Cliente(outputTB); 
        modo = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteLB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTB = new javax.swing.JTextArea();
        ventanaLB = new javax.swing.JLabel();
        timeoutLB = new javax.swing.JLabel();
        PuertoLB = new javax.swing.JLabel();
        modoCB = new javax.swing.JCheckBox();
        ventanaTB = new javax.swing.JTextField();
        archivoBTN = new javax.swing.JButton();
        comenzarBTN = new javax.swing.JButton();
        timeoutCB = new javax.swing.JTextField();
        puertoCB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clienteLB.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        clienteLB.setText("CLIENTE");

        outputTB.setColumns(20);
        outputTB.setRows(5);
        jScrollPane1.setViewportView(outputTB);

        ventanaLB.setText("Ventana");

        timeoutLB.setText("Timeout");

        PuertoLB.setText("Puerto inter.");

        modoCB.setText("Modo debug");
        modoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoCBActionPerformed(evt);
            }
        });

        ventanaTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventanaTBActionPerformed(evt);
            }
        });

        archivoBTN.setText("Seleccione el archivo");
        archivoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoBTNActionPerformed(evt);
            }
        });

        comenzarBTN.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 0, 24)); // NOI18N
        comenzarBTN.setText("Comenzar");
        comenzarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modoCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ventanaLB)
                                    .addComponent(timeoutLB)
                                    .addComponent(PuertoLB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ventanaTB, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(timeoutCB)
                                    .addComponent(puertoCB))
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(archivoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(comenzarBTN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(clienteLB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clienteLB)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ventanaLB)
                            .addComponent(ventanaTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeoutLB)
                            .addComponent(timeoutCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PuertoLB)
                            .addComponent(puertoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(archivoBTN)
                        .addGap(18, 18, 18)
                        .addComponent(modoCB)
                        .addGap(30, 30, 30)
                        .addComponent(comenzarBTN)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void archivoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoBTNActionPerformed
        try {                                           
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            StringBuilder fileContents = new StringBuilder((int) f.length());
            Scanner scanner = new Scanner(f);
            String lineSeparator = System.getProperty("line.separator");
            
            try {
                while (scanner.hasNextLine()) {
                    fileContents.append(scanner.nextLine() + lineSeparator);
                }
            } finally {
                scanner.close();
            }
            cliente.archivo = fileContents.toString();
            
        }   catch (FileNotFoundException ex) {
            Logger.getLogger(interfaz_cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_archivoBTNActionPerformed

    private void ventanaTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventanaTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventanaTBActionPerformed

    private void comenzarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarBTNActionPerformed
        if( (ventanaTB.getText().length()>0) 
                && (puertoCB.getText().length()>0)
                && (timeoutCB.getText().length()>0)
                && (cliente.archivo.length()>0)){
        cliente.tamano_ventana = Integer.parseInt(ventanaTB.getText());
        cliente.puerto_intemediario = Integer.parseInt(puertoCB.getText());
        cliente.timeout = Long.parseLong(timeoutCB.getText());
        cliente.modo = modo;
        cliente.start();
        } else {
            JOptionPane.showMessageDialog(null, "Suministre todos los inputs", "Warning",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_comenzarBTNActionPerformed

    private void modoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoCBActionPerformed
        modo = !modo;
    }//GEN-LAST:event_modoCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                interfaz_cliente interfaz = new interfaz_cliente();
                interfaz.setVisible(true);
                //new interfaz_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PuertoLB;
    private javax.swing.JButton archivoBTN;
    private javax.swing.JLabel clienteLB;
    private javax.swing.JButton comenzarBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox modoCB;
    private javax.swing.JTextArea outputTB;
    private javax.swing.JTextField puertoCB;
    private javax.swing.JTextField timeoutCB;
    private javax.swing.JLabel timeoutLB;
    private javax.swing.JLabel ventanaLB;
    private javax.swing.JTextField ventanaTB;
    // End of variables declaration//GEN-END:variables
}
